"""
NIST SP 800-53 Revision 5 Control Catalog.

This module provides validation functions for NIST SP 800-53 R5 control IDs.
Used by the OSCAL validator to ensure mapped controls exist in the official catalog.

Reference: https://csrc.nist.gov/projects/risk-management/sp800-53-controls/release/
"""

# NIST SP 800-53 R5 Complete Control Catalog
# Format: {Control-ID: Description}
NIST_SP_800_53_R5_CONTROLS = {
    # Access Control (AC) Family
    "AC-1": "Policy and Procedures",
    "AC-2": "Account Management",
    "AC-2(1)": "Account Management | Automated System Account Management",
    "AC-2(2)": "Account Management | Automated Privileged Access Management",
    "AC-2(3)": "Account Management | Disable Accounts",
    "AC-2(4)": "Account Management | Automated Audit Actions",
    "AC-2(5)": "Account Management | Access Reviews",
    "AC-2(6)": "Account Management | Dynamic Privilege Management",
    "AC-2(7)": "Account Management | Role-based Scheme",
    "AC-2(8)": "Account Management | Dynamic Access Control Based On Cryptographic Keys",
    "AC-2(9)": "Account Management | Shared and Group Account Identification",
    "AC-2(10)": "Account Management | Shared and Group Account Termination",
    "AC-2(11)": "Account Management | Usage Conditions",
    "AC-2(12)": "Account Management | Account Monitoring for Atypical Usage",
    "AC-2(13)": "Account Management | Disable Accounts for High-risk Individuals",
    "AC-3": "Access Enforcement",
    "AC-3(1)": "Access Enforcement | Restricted Access To Search Capability",
    "AC-3(2)": "Access Enforcement | Dual Authorization",
    "AC-3(3)": "Access Enforcement | Prerelease Access",
    "AC-3(4)": "Access Enforcement | Reverse Engineering",
    "AC-3(5)": "Access Enforcement | Security-relevant Information",
    "AC-3(6)": "Access Enforcement | Protection Of User And System Information",
    "AC-3(7)": "Access Enforcement | Role-based Access Control",
    "AC-3(8)": "Access Enforcement | Policy Down-load Capabilities",
    "AC-3(9)": "Access Enforcement | Controlled Release",
    "AC-3(10)": "Access Enforcement | Programmatic Access Enforcement",
    "AC-3(11)": "Access Enforcement | Restrict Access To Data At Rest",
    "AC-3(12)": "Access Enforcement | Assertion-based Access Control",
    "AC-3(13)": "Access Enforcement | Attribute-based Access Control",
    "AC-3(14)": "Access Enforcement | Individual Access Decision Review",
    "AC-3(15)": "Access Enforcement | Mandatory Access Control For Bit Alteration",
    "AC-3(16)": "Access Enforcement | Privilege Reduction Capabilities",
    "AC-4": "Information Flow Enforcement",
    "AC-4(1)": "Information Flow Enforcement | Object Security Attributes",
    "AC-4(2)": "Information Flow Enforcement | Processing Domains",
    "AC-4(3)": "Information Flow Enforcement | Dynamic Information Flow Control",
    "AC-4(4)": "Information Flow Enforcement | Content Check Before Transmission",
    "AC-4(5)": "Information Flow Enforcement | Embedded Data Types",
    "AC-4(6)": "Information Flow Enforcement | Metadata",
    "AC-4(7)": "Information Flow Enforcement | One-way Information Flows",
    "AC-4(8)": "Information Flow Enforcement | Security Policy Exceptions",
    "AC-4(9)": "Information Flow Enforcement | Human Review",
    "AC-4(10)": "Information Flow Enforcement | Enable Disable",
    "AC-4(11)": "Information Flow Enforcement | Configuration With Information Flow Restrictions",
    "AC-4(12)": "Information Flow Enforcement | Data Type Identifiers",
    "AC-4(13)": "Information Flow Enforcement | Decomposition Into Policy-Relevant Subcomponents",
    "AC-4(14)": "Information Flow Enforcement | Intra-system Separation and Segmentation",
    "AC-4(15)": "Information Flow Enforcement | Coding Techniques",
    "AC-4(16)": "Information Flow Enforcement | Information Flow Restrictions Based On Metadata",
    "AC-4(17)": "Information Flow Enforcement | Domain Authentication",
    "AC-4(18)": "Information Flow Enforcement | Security Policy Validation",
    "AC-4(19)": "Information Flow Enforcement | Termination of Information Flows on Compromises",
    "AC-4(20)": "Information Flow Enforcement | Approved Encryption Techniques",
    "AC-4(21)": "Information Flow Enforcement | Physical or Logical Separation Of Information Flows",
    "AC-5": "Separation of Duties",
    "AC-5(1)": "Separation of Duties | Automated Separation of Duties",
    "AC-5(2)": "Separation of Duties | Automated Execution",
    "AC-5(3)": "Separation of Duties | Dual Authorization",
    "AC-5(4)": "Separation of Duties | Auditable Events",
    "AC-6": "Least Privilege",
    "AC-6(1)": "Least Privilege | Authorize Access To Security Functions",
    "AC-6(2)": "Least Privilege | Non-privileged User Access",
    "AC-6(3)": "Least Privilege | Minimize Nonsecurity Functions",
    "AC-6(4)": "Least Privilege | Separate Processing Domains",
    "AC-6(5)": "Least Privilege | Restrict Access To User Sessions",
    "AC-6(6)": "Least Privilege | Privileged Access by Organization",
    "AC-6(7)": "Least Privilege | Review of User Privileges",
    "AC-6(8)": "Least Privilege | Privilege Levels for Code Execution",
    "AC-6(9)": "Least Privilege | Log Use Of Privileged Functions",
    "AC-6(10)": "Least Privilege | Prohibit Non-privileged Users from Executing Privileged Functions",
    "AC-7": "Unsuccessful Logon Attempts",
    "AC-7(1)": "Unsuccessful Logon Attempts | Automatic Action on Excessive Logon Failures",
    "AC-7(2)": "Unsuccessful Logon Attempts | Purge or Delay of Records",
    "AC-7(3)": "Unsuccessful Logon Attempts | Notify User on Previous Logon",
    "AC-8": "System Use Notification",
    "AC-8(1)": "System Use Notification | System Use Notification",
    "AC-8(2)": "System Use Notification | Acceptable Use Statements",
    "AC-9": "Previous Logon (Access) Notification",
    "AC-9(1)": "Previous Logon (Access) Notification | Subsequent Logon Notification",
    "AC-9(2)": "Previous Logon (Access) Notification | Unsuccessful Access Attempts",
    "AC-9(3)": "Previous Logon (Access) Notification | Additional Logon Information",
    "AC-9(4)": "Previous Logon (Access) Notification | Centralized Management",
    "AC-10": "Concurrent Session Control",
    "AC-10(1)": "Concurrent Session Control | User-initiated Logouts and Message Displays",
    "AC-10(2)": "Concurrent Session Control | Permitted Logon Times",
    "AC-11": "Session Lock and Termination",
    "AC-11(1)": "Session Lock and Termination | Pattern-hiding Displays",
    "AC-11(2)": "Session Lock and Termination | Re-authentication Displays",
    "AC-11(3)": "Session Lock and Termination | Automatic Session Termination",
    "AC-11(4)": "Session Lock and Termination | Termination Messages",
    "AC-12": "Session Termination",
    "AC-12(1)": "Session Termination | User-initiated Logouts",
    "AC-12(2)": "Session Termination | Termination of other Sessions",
    "AC-12(3)": "Session Termination | Disable Sessions",
    "AC-13": "Supervision and Review – Access Control",
    "AC-14": "Permitted Actions without Identification or Authentication",
    "AC-14(1)": "Permitted Actions without Identification or Authentication | Necessary Uses",
    "AC-15": "User-controlled Cryptographic Keys",
    "AC-16": "Security Attributes",
    "AC-16(1)": "Security Attributes | Dynamic Attribute Binding",
    "AC-16(2)": "Security Attributes | Attribute Dissemination",
    "AC-16(3)": "Security Attributes | Maintenance of Attribute Associations",
    "AC-16(4)": "Security Attributes | Association Preservation",
    "AC-16(5)": "Security Attributes | Attribute Scope",
    "AC-16(6)": "Security Attributes | Attribute Value Changes",
    "AC-16(7)": "Security Attributes | Consistent Attribute Interpretation",
    "AC-16(8)": "Security Attributes | Attribute Configuration by Authorized Individuals",
    "AC-16(9)": "Security Attributes | Attribute-based Information Flow Control",
    "AC-16(10)": "Security Attributes | Attribute Certificates",
    "AC-17": "Remote Access",
    "AC-17(1)": "Remote Access | Automated Monitoring and Control",
    "AC-17(2)": "Remote Access | Protection of Confidentiality and Integrity Using Encryption",
    "AC-17(3)": "Remote Access | Managed Access Control Points",
    "AC-17(4)": "Remote Access | Privileged Commands and Access",
    "AC-17(5)": "Remote Access | Monitoring for Unauthorized Connections",
    "AC-17(6)": "Remote Access | Protection of Information In Transit",
    "AC-17(7)": "Remote Access | Additional Access Controls",
    "AC-17(8)": "Remote Access | Disable Remote Activation of Sensors or Monitoring Devices",
    "AC-17(9)": "Remote Access | Disconnect or Disable Access",
    "AC-18": "Wireless Access",
    "AC-18(1)": "Wireless Access | Authentication and Encryption",
    "AC-18(2)": "Wireless Access | Protection of Wireless Access",
    "AC-18(3)": "Wireless Access | Detection of Unauthorized Wireless Access Points",
    "AC-18(4)": "Wireless Access | Restrictions on Wireless Use",
    "AC-18(5)": "Wireless Access | Antennas and Transmission Power Levels",
    "AC-19": "Access Control for Mobile Devices",
    "AC-19(1)": "Access Control for Mobile Devices | Device Identification and Registration",
    "AC-19(2)": "Access Control for Mobile Devices | Selective Functionality",
    "AC-19(3)": "Access Control for Mobile Devices | Document Handling and Protective Measures",
    "AC-19(4)": "Access Control for Mobile Devices | Encryption and Mechanisms",
    "AC-19(5)": "Access Control for Mobile Devices | Access Control Policy",
    "AC-20": "Use of External Information Systems",
    "AC-20(1)": "Use of External Information Systems | Limits on Authorized Use",
    "AC-20(2)": "Use of External Information Systems | Portable Storage Devices – Restricted Use",
    "AC-21": "Information Sharing",
    "AC-21(1)": "Information Sharing | Automated Decision Support System",
    "AC-21(2)": "Information Sharing | Information Search and Retrieval",
    "AC-22": "Publicly Accessible Content",
    "AC-22(1)": "Publicly Accessible Content | Automated Removal of Outdated Information",

    # Audit and Accountability (AU) Family
    "AU-1": "Audit and Accountability Policies and Procedures",
    "AU-2": "Audit Events",
    "AU-2(1)": "Audit Events | Compilation of Audit Records from Multiple Sources",
    "AU-2(2)": "Audit Events | Selection of Audit Events",
    "AU-2(3)": "Audit Events | Reviews and Adjustments",
    "AU-2(4)": "Audit Events | Privileged Functions",
    "AU-3": "Content of Audit Records",
    "AU-3(1)": "Content of Audit Records | User Identification",
    "AU-3(2)": "Content of Audit Records | Centralized Management of Planned Audit Record Content",
    "AU-3(3)": "Content of Audit Records | Limit Personally Identifiable Information Processing",
    "AU-4": "Audit Storage Capacity",
    "AU-4(1)": "Audit Storage Capacity | Transfer to Alternate Storage",
    "AU-5": "Response to Audit Processing Failures",
    "AU-5(1)": "Response to Audit Processing Failures | Immediate Actions",
    "AU-5(2)": "Response to Audit Processing Failures | Secondary Audit Logging Mechanism",
    "AU-5(3)": "Response to Audit Processing Failures | Provide Audit Record Reduction and Report Generation",
    "AU-5(4)": "Response to Audit Processing Failures | Log on Failure",
    "AU-6": "Audit Review, Analysis, and Reporting",
    "AU-6(1)": "Audit Review, Analysis, and Reporting | Automated Process Integration",
    "AU-6(2)": "Audit Review, Analysis, and Reporting | Automated Security Testing",
    "AU-6(3)": "Audit Review, Analysis, and Reporting | Correlate Audit Record Repositories",
    "AU-6(4)": "Audit Review, Analysis, and Reporting | Central Review and Analysis",
    "AU-6(5)": "Audit Review, Analysis, and Reporting | Integrated Analysis of Audit Records",
    "AU-6(6)": "Audit Review, Analysis, and Reporting | Correlation with Physical Monitoring",
    "AU-6(7)": "Audit Review, Analysis, and Reporting | Permitted Actions",
    "AU-6(8)": "Audit Review, Analysis, and Reporting | Full-text Analysis of Privileged Commands",
    "AU-6(9)": "Audit Review, Analysis, and Reporting | Correlation with Information from Nontechnical Sources",
    "AU-6(10)": "Audit Review, Analysis, and Reporting | Audit Level Adjustment",
    "AU-7": "Audit Reduction and Report Generation",
    "AU-7(1)": "Audit Reduction and Report Generation | Automatic Processing",
    "AU-7(2)": "Audit Reduction and Report Generation | Automatic Sort and Search",
    "AU-8": "Timestamp",
    "AU-8(1)": "Timestamp | Synchronization with Authoritative Time Source",
    "AU-8(2)": "Timestamp | Synchronization with Atomic Clocks",
    "AU-9": "Protection of Audit Information",
    "AU-9(1)": "Protection of Audit Information | Hardware Abstraction Layer",
    "AU-9(2)": "Protection of Audit Information | Audit Backup on Separate Hardware Component",
    "AU-9(3)": "Protection of Audit Information | Cryptographic Protection",
    "AU-9(4)": "Protection of Audit Information | Remote Access",
    "AU-9(5)": "Protection of Audit Information | Dual Authorization",
    "AU-9(6)": "Protection of Audit Information | Read-only Media",
    "AU-9(7)": "Protection of Audit Information | Store on Separate Component",
    "AU-10": "Non-repudiation",
    "AU-10(1)": "Non-repudiation | Replay Resistant Authentication Mechanisms",
    "AU-10(2)": "Non-repudiation | Information Integrity Check",
    "AU-10(3)": "Non-repudiation | Chain of Custody",
    "AU-10(4)": "Non-repudiation | Validate Binding of Information Producer Identity",
    "AU-10(5)": "Non-repudiation | Covered by Assertion",
    "AU-11": "Audit Record Retention",
    "AU-11(1)": "Audit Record Retention | Long-term Retrieval Capability",
    "AU-12": "Audit Generation",
    "AU-12(1)": "Audit Generation | System-wide and Time-correlated Audit Trail",
    "AU-12(2)": "Audit Generation | Standardized Formats",
    "AU-12(3)": "Audit Generation | Changes by Authorized Individuals",
    "AU-12(4)": "Audit Generation | Protect Audit Information",

    # Security Assessment and Authorization (CA) Family
    "CA-1": "Security Assessment and Authorization Policies and Procedures",
    "CA-2": "Security Assessments",
    "CA-2(1)": "Security Assessments | Independent Assessors",
    "CA-2(2)": "Security Assessments | Specialized Assessments",
    "CA-2(3)": "Security Assessments | External Organizations",
    "CA-3": "Information Exchange",
    "CA-3(1)": "Information Exchange | Unclassified Non-federal Information and System Connection / Use",
    "CA-3(2)": "Information Exchange | Unclassified Supplemental Information",
    "CA-3(3)": "Information Exchange | Unclassified Restricted Information",
    "CA-3(4)": "Information Exchange | Connections to Public Networks",
    "CA-3(5)": "Information Exchange | Restrictions on External System Connections",
    "CA-3(6)": "Information Exchange | Exchange with Federal Agencies or Organizations",
    "CA-3(7)": "Information Exchange | Interconnection Agreements",
    "CA-3(8)": "Information Exchange | Trusted Partner Connections",
    "CA-4": "Security Certification",
    "CA-5": "Plan of Action and Milestones",
    "CA-5(1)": "Plan of Action and Milestones | Automation Support for Accuracy and Currency",
    "CA-6": "Security Authorization",
    "CA-6(1)": "Security Authorization | Joint Authorization",
    "CA-6(2)": "Security Authorization | Mutual Acceptance",
    "CA-6(3)": "Security Authorization | Continuous Monitoring",
    "CA-7": "Continuous Monitoring",
    "CA-7(1)": "Continuous Monitoring | Independent Assessment",
    "CA-7(2)": "Continuous Monitoring | Automation Support for Monitoring",
    "CA-7(3)": "Continuous Monitoring | Trend Analysis",
    "CA-7(4)": "Continuous Monitoring | Risk Monitoring",
    "CA-8": "Penetration Testing",
    "CA-8(1)": "Penetration Testing | Automated Execution of Penetration Testing Tools",
    "CA-9": "Internal System Connections",
    "CA-9(1)": "Internal System Connections | Compliance Check",

    # Configuration Management (CM) Family
    "CM-1": "Configuration Management Policies and Procedures",
    "CM-2": "Baseline Configuration",
    "CM-2(1)": "Baseline Configuration | Reviews and Updates",
    "CM-2(2)": "Baseline Configuration | Automation Support for Accuracy and Currency",
    "CM-2(3)": "Baseline Configuration | Retention of Previous Configurations",
    "CM-2(4)": "Baseline Configuration | Authorized Changes",
    "CM-2(5)": "Baseline Configuration | Mapped to Current Operational Environment",
    "CM-2(6)": "Baseline Configuration | Development and Test Environments",
    "CM-2(7)": "Baseline Configuration | Configure Systems, Components, or Devices",
    "CM-3": "Change Control",
    "CM-3(1)": "Change Control | Automated Process Integration",
    "CM-3(2)": "Change Control | Testing, Validation, and Documentation",
    "CM-3(3)": "Change Control | Signed Components",
    "CM-3(4)": "Change Control | Security Relevant Changes",
    "CM-3(5)": "Change Control | Access Restrictions for Change",
    "CM-3(6)": "Change Control | Limit Change Packages",
    "CM-4": "Impact Analyses",
    "CM-4(1)": "Impact Analyses | Separate Testing Environments",
    "CM-4(2)": "Impact Analyses | Verification of Controls",
    "CM-5": "Access Restrictions for Change",
    "CM-5(1)": "Access Restrictions for Change | Automated Access Enforcement",
    "CM-5(2)": "Access Restrictions for Change | Limit Production / Operational Removals",
    "CM-5(3)": "Access Restrictions for Change | Signed Components",
    "CM-5(4)": "Access Restrictions for Change | Dual Authorization",
    "CM-5(5)": "Access Restrictions for Change | Privilege Limitation and Testing",
    "CM-5(6)": "Access Restrictions for Change | Limit Library Privileges",
    "CM-5(7)": "Access Restrictions for Change | Automatic Implementation of Security Relevant Changes",
    "CM-6": "Configuration Settings",
    "CM-6(1)": "Configuration Settings | Automated Central Management, Application, and Verification",
    "CM-6(2)": "Configuration Settings | Respond to Unauthorized Changes",
    "CM-6(3)": "Configuration Settings | Automation Support for Compliance Monitoring",
    "CM-6(4)": "Configuration Settings | Allow / Disallow Software and Firmware Installations",
    "CM-6(5)": "Configuration Settings | Restrict Software Installation",
    "CM-6(6)": "Configuration Settings | Configuration Management Tools",
    "CM-6(7)": "Configuration Settings | Reduction of Functionality",
    "CM-6(8)": "Configuration Settings | Prevent Unauthorized Changes",
    "CM-6(9)": "Configuration Settings | Configure Systems, Components, Devices, or Networks Consistent with Organizational Cybersecurity Policies",
    "CM-7": "Software, Firmware, and Information Technology Hardware Installations",
    "CM-7(1)": "Software, Firmware, and Information Technology Hardware Installations | Centralized Management",
    "CM-7(2)": "Software, Firmware, and Information Technology Hardware Installations | Automatic Software Updates",
    "CM-7(3)": "Software, Firmware, and Information Technology Hardware Installations | versioning Tool",
    "CM-7(4)": "Software, Firmware, and Information Technology Hardware Installations | Authorize Software / Firmware Installation",
    "CM-7(5)": "Software, Firmware, and Information Technology Hardware Installations | Prohibit Installation of Unauthorized Software / Firmware",
    "CM-7(6)": "Software, Firmware, and Information Technology Hardware Installations | Installation and Use Restrictions",
    "CM-7(7)": "Software, Firmware, and Information Technology Hardware Installations | Removal of Unauthorized Software / Firmware",
    "CM-7(8)": "Software, Firmware, and Information Technology Hardware Installations | Automatic Freeze, Thaw, And Lock",
    "CM-7(9)": "Software, Firmware, and Information Technology Hardware Installations | Prohibit Activation of Features, Ports, Protocols, and Services",
    "CM-8": "Information System Component Inventory",
    "CM-8(1)": "Information System Component Inventory | Automated Maintenance, Including Updating",
    "CM-8(2)": "Information System Component Inventory | Automated Asset Management",
    "CM-8(3)": "Information System Component Inventory | Software Inventory",
    "CM-8(4)": "Information System Component Inventory | Accountability and Responsibility",
    "CM-8(5)": "Information System Component Inventory | No Duplicate Accounting of Components",
    "CM-8(6)": "Information System Component Inventory | Assessed and Approved Components",
    "CM-8(7)": "Information System Component Inventory | Centralized Repository",
    "CM-8(8)": "Information System Component Inventory | Automated Updating",
    "CM-9": "Configuration Change Control and Release Management",
    "CM-9(1)": "Configuration Change Control and Release Management | Advance Notification",
    "CM-9(2)": "Configuration Change Control and Release Management | Security Representative Approval",
    "CM-9(3)": "Configuration Change Control and Release Management | Automated Enforcement and Compliance Analysis",
    "CM-10": "Software Use Restrictions",
    "CM-10(1)": "Software Use Restrictions | License Compliance",
    "CM-10(2)": "Software Use Restrictions | Monitoring Compliance",
    "CM-11": "User-installed Software",
    "CM-11(1)": "User-installed Software | Alerts For Unauthorized Installations",
    "CM-11(2)": "User-installed Software | Software Installation With Privileged Status",
    "CM-11(3)": "User-installed Software | Prohibited Software and Licenses",
    "CM-12": "Information Location",
    "CM-12(1)": "Information Location | Automated Tools and Techniques",
    "CM-13": "Data Handling and Retention",
    "CM-13(1)": "Data Handling and Retention | Centralized Capability",
    "CM-13(2)": "Data Handling and Retention | Automated Implementation",
    "CM-14": "Protect Software and Information Integrity",
    "CM-14(1)": "Protect Software and Information Integrity | Integrity Verification",

    # Identification and Authentication (IA) Family
    "IA-1": "Identification and Authentication Policies and Procedures",
    "IA-2": "Authentication",
    "IA-2(1)": "Authentication | Multi-factor Authentication To Privileged Accounts",
    "IA-2(2)": "Authentication | Multi-factor Authentication For Remote Access",
    "IA-2(3)": "Authentication | Multi-factor Authentication On Privileged And Non-privileged Accounts",
    "IA-2(4)": "Authentication | Multi-factor Authentication (Including Push Notifications) Upon Access to Privileged Accounts For Interactive Sessions And / Or Device Connection States",
    "IA-2(5)": "Authentication | Device-specific Credentials",
    "IA-2(6)": "Authentication | Implementation Of Multifactor Authentication For Access To Privileged Accounts Such That One Of The Factors Is Provided By A Device That The User Possesses",
    "IA-2(7)": "Authentication | Multi-factor Authentication For Access To Non-privileged Accounts",
    "IA-2(8)": "Authentication | Access To Accounts – Organization-defined Subset",
    "IA-2(9)": "Authentication | Network Access To Non-privileged Accounts – Logic Errors",
    "IA-2(10)": "Authentication | Single Sign-on (SSO)",
    "IA-2(11)": "Authentication | Remote Access – Protection Of Authentication Credentials",
    "IA-2(12)": "Authentication | Acceptance Of Externally-provided Credentials",
    "IA-2(13)": "Authentication | Out-of-band Authentication",
    "IA-2(14)": "Authentication | Lockout After Logon Attempts",
    "IA-2(15)": "Authentication | Replay Resistant Authentication Mechanisms",
    "IA-3": "Device Identification and Authentication",
    "IA-3(1)": "Device Identification and Authentication | Cryptographic and Biometric Identification and Authentication",
    "IA-3(2)": "Device Identification and Authentication | Cryptographically Bind Identity",
    "IA-3(3)": "Device Identification and Authentication | Dynamic Address Allocation",
    "IA-3(4)": "Device Identification and Authentication | Device Attributes",
    "IA-4": "Identifier Management",
    "IA-4(1)": "Identifier Management | Centralized Management",
    "IA-4(2)": "Identifier Management | Associated With User or Device",
    "IA-4(3)": "Identifier Management | Multiple Identifiers",
    "IA-4(4)": "Identifier Management | Identify User Status",
    "IA-4(5)": "Identifier Management | Dynamic Identifiers",
    "IA-4(6)": "Identifier Management | Cross-organization Management",
    "IA-4(7)": "Identifier Management | In-band and Out-of-band Identifiers",
    "IA-5": "Authentication",
    "IA-5(1)": "Authentication | Password-based Authentication",
    "IA-5(2)": "Authentication | Public Key Infrastructure Certificates",
    "IA-5(3)": "Authentication | In-person Or Trusted Third-party Registration",
    "IA-5(4)": "Authentication | Automated Password Strength Determination and Generation",
    "IA-5(5)": "Authentication | Change Authenticated Information",
    "IA-5(6)": "Authentication | Protection Of Authenticators",
    "IA-5(7)": "Authentication | No Embedded Unencrypted Static Authenticators",
    "IA-5(8)": "Authentication | Multiple Information System Accounts",
    "IA-5(9)": "Authentication | Federated Credential Management",
    "IA-5(10)": "Authentication | Cryptographic Storage of Credentials",
    "IA-5(11)": "Authentication | Hardware Tokens",
    "IA-5(12)": "Authentication | Passphrases",
    "IA-5(13)": "Authentication | Restrictive Authenticators",
    "IA-6": "Authentication Feedback",
    "IA-6(1)": "Authentication Feedback | Obscure Feedback of Authentication Information",
    "IA-6(2)": "Authentication Feedback | Obscure Feedback Of Authentication Information",
    "IA-7": "Cryptographic Module Authentication",
    "IA-8": "Identification and Authentication (Non-organizational Users)",
    "IA-8(1)": "Identification and Authentication (Non-organizational Users) | Acceptance of Credentials from Other Federal Agencies",
    "IA-8(2)": "Identification and Authentication (Non-organizational Users) | Acceptance of Third-party Credentials",
    "IA-8(3)": "Identification and Authentication (Non-organizational Users) | Use Of FICAM-approved Products",
    "IA-8(4)": "Identification and Authentication (Non-organizational Users) | Federated Identity",
    "IA-9": "Service Identification and Authentication",
    "IA-10": "Adaptive Identification and Authentication",
    "IA-10(1)": "Adaptive Identification and Authentication | Anomalous Activities",
    "IA-10(2)": "Adaptive Identification and Authentication | Identification and Authentication Decisions",
    "IA-10(3)": "Adaptive Identification and Authentication | Challenge-response Authentication",
    "IA-10(4)": "Adaptive Identification and Authentication | Risk-based Response",
    "IA-10(5)": "Adaptive Identification and Authentication | Awareness Prompts",
    "IA-11": "Fail-safe Defaults",
    "IA-12": "Cryptographic Key Establishment and Management",
    "IA-12(1)": "Cryptographic Key Establishment and Management | Key Escrow",
    "IA-12(2)": "Cryptographic Key Establishment and Management | Symmetric Keys",
    "IA-12(3)": "Cryptographic Key Establishment and Management | Public Keys",
    "IA-12(4)": "Cryptographic Key Establishment and Management | Roles and Responsibilities",
    "IA-12(5)": "Cryptographic Key Establishment and Management | Key Escrow and Recovery",

    # System and Communications Protection (SC) Family
    "SC-1": "System and Communications Protection Policies and Procedures",
    "SC-2": "Application Partitioning",
    "SC-3": "Security Function Isolation",
    "SC-3(1)": "Security Function Isolation | Hardware Separation",
    "SC-3(2)": "Security Function Isolation | Access to Security Functions",
    "SC-3(3)": "Security Function Isolation | Minimize Nonsecurity Functions",
    "SC-3(4)": "Security Function Isolation | Module-based Isolation",
    "SC-4": "Information in Shared Shared Resources",
    "SC-4(1)": "Information in Shared Shared Resources | Restrict Access To Shared Resources",
    "SC-5": "Denial-of-service Protection",
    "SC-5(1)": "Denial-of-service Protection | Restrict Inputs To Trusted Sources and Limit Cardinality",
    "SC-5(2)": "Denial-of-service Protection | Implement Blue-team Exercises",
    "SC-5(3)": "Denial-of-service Protection | Detection and Monitoring",
    "SC-5(4)": "Denial-of-service Protection | Failure Mode Denial of Service Protection",
    "SC-6": "Resource Availability",
    "SC-6(1)": "Resource Availability | Establish Resilient Service-level Objectives",
    "SC-7": "Boundary Protection",
    "SC-7(1)": "Boundary Protection | Monitored Managed Interface Points",
    "SC-7(2)": "Boundary Protection | Deny By Default - Allow By Exception",
    "SC-7(3)": "Boundary Protection | Access Points",
    "SC-7(4)": "Boundary Protection | External Telecommunications Connections",
    "SC-7(5)": "Boundary Protection | Deny By Default - Allow By Exception",
    "SC-7(6)": "Boundary Protection | Reachability Limitatons",
    "SC-7(7)": "Boundary Protection | Split Tunneling For Remote User Sessions",
    "SC-7(8)": "Boundary Protection | Route Traffic To Authenticated Proxy Servers",
    "SC-7(9)": "Boundary Protection | Restrict Connectivity To External Networks",
    "SC-7(10)": "Boundary Protection | Prevent Exfiltration Of Information",
    "SC-7(11)": "Boundary Protection | Restrict Information System Connections To External Systems",
    "SC-7(12)": "Boundary Protection | Host-based Protection",
    "SC-7(13)": "Boundary Protection | Isolation of Information System Components",
    "SC-7(14)": "Boundary Protection | Protects Against Unauthorized Physical Connections",
    "SC-7(15)": "Boundary Protection | Discontinuous Connections",
    "SC-7(16)": "Boundary Protection | Prevent Discovery of System Components",
    "SC-7(17)": "Boundary Protection | Segregation of User Sessions",
    "SC-7(18)": "Boundary Protection | Fail Secure",
    "SC-7(19)": "Boundary Protection | Block Communication From Non-organizationally Configured Sources",
    "SC-7(20)": "Boundary Protection | User-initiated Boundary Protections",
    "SC-7(21)": "Boundary Protection | Isolation of System Components",
    "SC-7(22)": "Boundary Protection | Separate Subnets To Isolate Functions",
    "SC-7(23)": "Boundary Protection | Disable Unused Ports and Protocols",
    "SC-7(24)": "Boundary Protection | Management Traffic Isolation",
    "SC-7(25)": "Boundary Protection | Isolation From Unclassified Networks",
    "SC-8": "Transmission Confidentiality and Integrity",
    "SC-8(1)": "Transmission Confidentiality and Integrity | Cryptographic Or Alternative Physical Protection",
    "SC-8(2)": "Transmission Confidentiality and Integrity | Pre- and Post-transmission Handling",
    "SC-8(3)": "Transmission Confidentiality and Integrity | Cryptographic Strength",
    "SC-8(4)": "Transmission Confidentiality and Integrity | Conceal Flow Characteristics",
    "SC-9": "Transmission of Security Parameters",
    "SC-9(1)": "Transmission of Security Parameters | Cryptographically Protect Security Parameters",
    "SC-10": "Network Disconnect",
    "SC-10(1)": "Network Disconnect | Termination Based on Inactivity",
    "SC-10(2)": "Network Disconnect | Termination by User",
    "SC-10(3)": "Network Disconnect | Termination of User-initiated Logical Sessions",
    "SC-10(4)": "Network Disconnect | User-initiated Logouts",
    "SC-10(5)": "Network Disconnect | Circuitry Disconnection",
    "SC-11": "Trusted Path",
    "SC-11(1)": "Trusted Path | Irrefutable Source Authentication",
    "SC-11(2)": "Trusted Path | Confidentiality Guarantees",
    "SC-11(3)": "Trusted Path | Unique Confirmation Mechanisms",
    "SC-12": "Cryptographic Key Establishment and Management",
    "SC-12(1)": "Cryptographic Key Establishment and Management | Availability",
    "SC-12(2)": "Cryptographic Key Establishment and Management | Symmetric Keys",
    "SC-12(3)": "Cryptographic Key Establishment and Management | Public Keys",
    "SC-12(4)": "Cryptographic Key Establishment and Management | Dual Control Of Long-term Key Management Keys",
    "SC-12(5)": "Cryptographic Key Establishment and Management | Constraint On Key Use",
    "SC-12(6)": "Cryptographic Key Establishment and Management | Reevaluation of Cryptographic Keys",
    "SC-12(7)": "Cryptographic Key Establishment and Management | Key Agreement and Key Transport",
    "SC-12(8)": "Cryptographic Key Establishment and Management | Key Escrow",
    "SC-12(9)": "Cryptographic Key Establishment and Management | Cryptographic Key Management and Key Establishment",
    "SC-13": "Cryptographic Protection",
    "SC-13(1)": "Cryptographic Protection | Cryptographic Modules",
    "SC-13(2)": "Cryptographic Protection | Cryptographic Standards and Mechanisms",
    "SC-13(3)": "Cryptographic Protection | Cryptographic Hardware",
    "SC-14": "Public Access Protections",
    "SC-15": "Collaborative Computing Devices",
    "SC-15(1)": "Collaborative Computing Devices | Physical or Logical Disconnect",
    "SC-15(2)": "Collaborative Computing Devices | Disabling and Removal in Secure Facility",
    "SC-15(3)": "Collaborative Computing Devices | Disabling and Removal",
    "SC-15(4)": "Collaborative Computing Devices | Explicit User Consent",
    "SC-15(5)": "Collaborative Computing Devices | Physical Safeguards",
    "SC-15(6)": "Collaborative Computing Devices | Explicit User Consent For Explicit Connections",
    "SC-15(7)": "Collaborative Computing Devices | Explicit User Consent To Participate",
    "SC-15(8)": "Collaborative Computing Devices | Disable Devices and Features By Default",
    "SC-16": "Transmission of Sensitive Information",
    "SC-16(1)": "Transmission of Sensitive Information | Cryptographic Protection",
    "SC-16(2)": "Transmission of Sensitive Information | Pre- and Post-transmission Handling",
    "SC-16(3)": "Transmission of Sensitive Information | Unclassified Network Segmentation",
    "SC-16(4)": "Transmission of Sensitive Information | Alternate Authenticated Encryption",
    "SC-16(5)": "Transmission of Sensitive Information | Dedicated Communications Links",
    "SC-17": "Public Key Infrastructure and Certificates",
    "SC-17(1)": "Public Key Infrastructure and Certificates | Issuer Recognizable to Public",
    "SC-17(2)": "Public Key Infrastructure and Certificates | Third-party Issued Certificates",
    "SC-17(3)": "Public Key Infrastructure and Certificates | Certificates For Cryptographic Mechanisms",
    "SC-17(4)": "Public Key Infrastructure and Certificates | Public Key Infrastructure Certificates",
    "SC-17(5)": "Public Key Infrastructure and Certificates | Certificate Management",
    "SC-17(6)": "Public Key Infrastructure and Certificates | Certificate Pinning",
    "SC-17(7)": "Public Key Infrastructure and Certificates | Single-use Certificates",
    "SC-17(8)": "Public Key Infrastructure and Certificates | Bind Identity Information to Certificate",
    "SC-17(9)": "Public Key Infrastructure and Certificates | Cryptographic Key Establishment and Management",
    "SC-18": "Mobile Code",
    "SC-18(1)": "Mobile Code | Verify System Modifications",
    "SC-18(2)": "Mobile Code | Identify Executable Originating Code",
    "SC-18(3)": "Mobile Code | Prohibit Automatic Execution",
    "SC-18(4)": "Mobile Code | Prevent Download and Execution",
    "SC-18(5)": "Mobile Code | Allow Execution Only In Sandboxed Environments",
    "SC-19": "Voice over Internet Protocol",
    "SC-19(1)": "Voice over Internet Protocol | Encrypt Voice Communications",
    "SC-19(2)": "Voice over Internet Protocol | Fail Secure",
    "SC-20": "Secure Name / Address Resolution Service (DNSSEC)",
    "SC-20(1)": "Secure Name / Address Resolution Service (DNSSEC) | Cryptographic Signature Verification",
    "SC-20(2)": "Secure Name / Address Resolution Service (DNSSEC) | Information Origin Authentication and Integrity Verification",
    "SC-21": "Secondary Name Resolution",
    "SC-21(1)": "Secondary Name Resolution | Data Origin and Integrity",
    "SC-22": "Architecture and Provisioning for Name / Address Resolution Service",
    "SC-22(1)": "Architecture and Provisioning for Name / Address Resolution Service | Redundancy and Managed Failover",
    "SC-22(2)": "Architecture and Provisioning for Name / Address Resolution Service | Distributed Architecture With Synchronization",
    "SC-23": "Session Authenticity",
    "SC-23(1)": "Session Authenticity | Detect Session Fixation Attacks",
    "SC-23(2)": "Session Authenticity | Unique Session Identifiers",
    "SC-23(3)": "Session Authenticity | Unique Session Identifiers With Randomization",
    "SC-24": "Fail in Known State",
    "SC-24(1)": "Fail in Known State | Transmit Authenticated Recovery Data",
    "SC-25": "Thin Nodes",
    "SC-25(1)": "Thin Nodes | Attribute-based Policies",
    "SC-26": "Decoupled or Physically Isolated Subsystems",
    "SC-26(1)": "Decoupled or Physically Isolated Subsystems | Physically or Logically Separated Processing Domains",
    "SC-27": "Platform-independent Applications",
    "SC-27(1)": "Platform-independent Applications | Minimize Non-essential Functionality",
    "SC-28": "Specification-driven Enforcement of System Interfaces",
    "SC-28(1)": "Specification-driven Enforcement of System Interfaces | Automated Enforcement of Access To System Interfaces",
    "SC-29": "Heterogeneous Resilience",
    "SC-29(1)": "Heterogeneous Resilience | Diversity of Information Processing Elements",
    "SC-30": "Concealment and Misdirection",
    "SC-30(1)": "Concealment and Misdirection | Virtualization and Sandboxing",
    "SC-30(2)": "Concealment and Misdirection | Randomness",
    "SC-30(3)": "Concealment and Misdirection | Change Processing and Storage Locations",
    "SC-30(4)": "Concealment and Misdirection | Disguise System Components",
    "SC-30(5)": "Concealment and Misdirection | Concealment of System Components",
    "SC-31": "Covert Channels",
    "SC-31(1)": "Covert Channels | Reduce Covert Channels",
    "SC-31(2)": "Covert Channels | Reduce Covert Channels",
    "SC-31(3)": "Covert Channels | Authorized Covert Channels",
    "SC-32": "System Partitioning",
    "SC-32(1)": "System Partitioning | Separate Physical or Logical Domains",
    "SC-33": "Transmission Preparation Integrity",
    "SC-33(1)": "Transmission Preparation Integrity | Verify Integrity Before Acceptance",
    "SC-34": "Non-modifiable Executable Content",
    "SC-34(1)": "Non-modifiable Executable Content | No Writable Storage Media",
    "SC-34(2)": "Non-modifiable Executable Content | Removable Media",
    "SC-34(3)": "Non-modifiable Executable Content | Hardware-based Protection",
    "SC-35": "External Route Servers",
    "SC-35(1)": "External Route Servers | Separate Routing Domains",
    "SC-36": "Distributed Processing and Storage",
    "SC-36(1)": "Distributed Processing and Storage | Distribute To Multiple Locations",
    "SC-36(2)": "Distributed Processing and Storage | Resilience and Survivability",
    "SC-37": "Out-of-band Channels",
    "SC-37(1)": "Out-of-band Channels | Ensure Delivery and Timeliness",
    "SC-38": "Operations Security",
    "SC-38(1)": "Operations Security | Optimize Use of Operational Security",
    "SC-39": "Process Isolation",
    "SC-39(1)": "Process Isolation | Hardware Separation",
    "SC-40": "Wireless Use Restrictions",
    "SC-40(1)": "Wireless Use Restrictions | Monitoring and Enforcement",
    "SC-41": "Port and I/O Device Access",
    "SC-41(1)": "Port and I/O Device Access | Restrict Use Of Universal Serial Bus Ports",
    "SC-42": "Sensor Capability and Use",
    "SC-42(1)": "Sensor Capability and Use | Sensor Activation Capability",
    "SC-42(2)": "Sensor Capability and Use | Authorized Activation of Sensor Capability",
    "SC-42(3)": "Sensor Capability and Use | Unauthorized Activation",
    "SC-42(4)": "Sensor Capability and Use | Minimize Sensor Capability and Use",
    "SC-43": "Usage Restrictions",
    "SC-43(1)": "Usage Restrictions | Authorized Use Conditions",
    "SC-44": "Decommissioning of Information Systems",
    "SC-44(1)": "Decommissioning of Information Systems | Certification of Secure Decommissioning",

    # Program Management (PM) Family
    "PM-1": "Information Security Program Policies and Procedures",
    "PM-2": "Senior Information Security Officer",
    "PM-3": "Information Security Resources",
    "PM-4": "Plan of Action and Milestones Process",
    "PM-5": "System Security Plan Review",
    "PM-6": "Information Security Measures Of Performance",
    "PM-7": "Enterprise Architecture",
    "PM-8": "Risk Management Program",
    "PM-9": "Risk Assessment",
    "PM-10": "Authorization Process",
    "PM-11": "Mission Criticality Analysis",
    "PM-12": "Insider Threat Program",
    "PM-13": "Supply Chain Risk Management",
    "PM-14": "Testing, Training, And Monitoring",
    "PM-15": "Contacts, Contingency Planning, And Incident Response",
    "PM-16": "Threat and Vulnerability Management",
    "PM-17": "Effectiveness of Information Security Measures",
    "PM-18": "Data Governance",
    "PM-19": "Developing Enterprise Processes",
    "PM-20": "Dissemination of Security Awareness and Training Program Information",
    "PM-21": "Accounting Of Contractors And Vendors",
    "PM-22": "Continuous Monitoring Program",
    "PM-23": "System Development Life Cycle",
    "PM-24": "Insider Threat Monitoring and Response",
    "PM-25": "Organizational Processes and Systems",
    "PM-26": "Organizational Processes and Systems",
    "PM-27": "Supply Chain Risk Management Program",
    "PM-28": "Purposeful and Targeted Recruitment",
    "PM-29": "Insider Threat Program Leadership",
    "PM-30": "Rules of Behavior",
    "PM-31": "Continuous Monitoring Strategy and Implementation",
    "PM-32": "Purposeful and Targeted Recruitment",
    "PM-33": "Component Inventory",

    # Planning (PL) Family
    "PL-1": "Security Planning Policies and Procedures",
    "PL-2": "System Security Plan",
    "PL-2(1)": "System Security Plan | Information Exchange",
    "PL-2(2)": "System Security Plan | Sharing Responsibility",
    "PL-2(3)": "System Security Plan | Plan / Procedure Integration",
    "PL-4": "Rules of Behavior",
    "PL-4(1)": "Rules of Behavior | Accessibility",
    "PL-4(2)": "Rules of Behavior | Acknowledgment",
    "PL-6": "Security-related Activity Planning",
    "PL-6(1)": "Security-related Activity Planning | Integrated Planning",
    "PL-7": "Concept of Operations",
    "PL-8": "Information Security Architecture",
    "PL-8(1)": "Information Security Architecture | Acquired Information Systems",
    "PL-9": "Central Management",
    "PL-9(1)": "Central Management | Coordination Among Organizational Entities",
    "PL-10": "Baseline Selection",
    "PL-10(1)": "Baseline Selection | Mod Priority Baseline",
    "PL-11": "Information Security Governance",
    "PL-11(1)": "Information Security Governance | Mission / Business Process Definition",

    # Supply Chain Risk Management (SR) Family
    "SR-1": "Supply Chain Risk Management Policies and Procedures",
    "SR-2": "Supply Chain Risk Management Plan",
    "SR-2(1)": "Supply Chain Risk Management Plan | Establish SCRM Team",
    "SR-3": "Supply Chain Controls and Processes",
    "SR-3(1)": "Supply Chain Controls and Processes | Supplier Reviews",
    "SR-3(2)": "Supply Chain Controls and Processes | Acquisition Security Requirements",
    "SR-4": "Provenance",
    "SR-4(1)": "Provenance | Validation of Provenance Data",
    "SR-5": "Acquisition Strategies, Tools, and Methods",
    "SR-5(1)": "Acquisition Strategies, Tools, and Methods | Standardized Processes and Procedures",
    "SR-5(2)": "Acquisition Strategies, Tools, and Methods | Quality Metrics",
    "SR-6": "Supplier Assessments and Reviews",
    "SR-6(1)": "Supplier Assessments and Reviews | Specialized Assessments",
    "SR-7": "Supply Chain Operations Security",
    "SR-7(1)": "Supply Chain Operations Security | Organizational Processes",
    "SR-8": "Notification Agreements",
    "SR-8(1)": "Notification Agreements | Deviations For National Interests",
    "SR-9": "Supply Chain Transparency and Integrity",
    "SR-9(1)": "Supply Chain Transparency and Integrity | Inspection and Analysis of Hardware and Firmware",
    "SR-10": "Hardware and Firmware Source Identification and Traceability",
    "SR-10(1)": "Hardware and Firmware Source Identification and Traceability | Validation of Sources",
    "SR-11": "Counterintelligence Agreements",
    "SR-11(1)": "Counterintelligence Agreements | Standardized Processes",
    "SR-12": "Supplier Risk Assessment Updates",
    "SR-12(1)": "Supplier Risk Assessment Updates | Automated Processes",

    # Contingency Planning (CP) Family
    "CP-1": "Contingency Planning Policies and Procedures",
    "CP-2": "Contingency Plan",
    "CP-2(1)": "Contingency Plan | Coordinate With Related Plans",
    "CP-2(2)": "Contingency Plan | Capacity Planning",
    "CP-2(3)": "Contingency Plan | Resume All Missions and Business Functions",
    "CP-2(4)": "Contingency Plan | Resume Key Missions and Business Functions",
    "CP-2(5)": "Contingency Plan | Continue Mission and Business Functions",
    "CP-3": "Contingency Training",
    "CP-3(1)": "Contingency Training | Sophisticated Simulations",
    "CP-3(2)": "Contingency Training | Alternate Processing Site",
    "CP-4": "Contingency Plan Testing",
    "CP-4(1)": "Contingency Plan Testing | Coordinate With Related Plans",
    "CP-4(2)": "Contingency Plan Testing | Alternate Processing Site",
    "CP-4(3)": "Contingency Plan Testing | Full System Restoration",
    "CP-4(4)": "Contingency Plan Testing | Full System Restoration and Alternate Processing Site",
    "CP-5": "Contingency Plan Update",
    "CP-6": "Alternate Processing Site",
    "CP-6(1)": "Alternate Processing Site | Separation From Primary Site",
    "CP-6(2)": "Alternate Processing Site | Accessibility",
    "CP-6(3)": "Alternate Processing Site | One-time Notification",
    "CP-7": "Disaster Recovery Site",
    "CP-7(1)": "Disaster Recovery Site | Separation From Primary Site",
    "CP-7(2)": "Disaster Recovery Site | Accessibility",
    "CP-7(3)": "Disaster Recovery Site | One-time Notification",
    "CP-7(4)": "Disaster Recovery Site | Prepare For Activation",
    "CP-8": "Telecommunications Services",
    "CP-8(1)": "Telecommunications Services | Priority Queuing",
    "CP-8(2)": "Telecommunications Services | Single Points of Failure",
    "CP-8(3)": "Telecommunications Services | Separation of Primary and Alternate Providers",
    "CP-8(4)": "Telecommunications Services | Diversity of Carrier Services",
    "CP-9": "System Backup",
    "CP-9(1)": "System Backup | Testing for Restoration",
    "CP-9(2)": "System Backup | Test Restoration Using Sampling",
    "CP-9(3)": "System Backup | Separate Storage for Critical Information",
    "CP-9(4)": "System Backup | Protection From Unauthorized Access",
    "CP-9(5)": "System Backup | Transfer To Alternate Storage",
    "CP-9(6)": "System Backup | Redundant Secondary Servers",
    "CP-9(7)": "System Backup | Dual Authorization For Deletion or Destruction",
    "CP-9(8)": "System Backup | Cryptographic Protection",
    "CP-10": "Information System Recovery and Reconstitution",
    "CP-10(1)": "Information System Recovery and Reconstitution | Comparator Analysis",
    "CP-10(2)": "Information System Recovery and Reconstitution | Transaction Rollback",
    "CP-10(3)": "Information System Recovery and Reconstitution | Restore To Known Secure State",
    "CP-10(4)": "Information System Recovery and Reconstitution | Restore Within Time Period",
    "CP-10(5)": "Information System Recovery and Reconstitution | Failover Capability",
    "CP-10(6)": "Information System Recovery and Reconstitution | Component Protection",
    "CP-11": "Alternate Communications Protocols",
    "CP-11(1)": "Alternate Communications Protocols | Priority Of Alternate Protocols",
    "CP-12": "Safe Mode",
    "CP-12(1)": "Safe Mode | Justification Of Safe Mode",
    "CP-13": "Alternate Computing Environment",
    "CP-13(1)": "Alternate Computing Environment | Priority",
    "CP-13(2)": "Alternate Computing Environment | Transition Capability",
    "CP-13(3)": "Alternate Computing Environment | Prepare For Activation",
    "CP-13(4)": "Alternate Computing Environment | Separation From Primary Site",

    # Incident Response (IR) Family
    "IR-1": "Incident Response Policies and Procedures",
    "IR-2": "Incident Response Training",
    "IR-2(1)": "Incident Response Training | Simulations / Exercises",
    "IR-2(2)": "Incident Response Training | Automated Training",
    "IR-2(3)": "Incident Response Training | Breach Response",
    "IR-3": "Incident Response Testing",
    "IR-3(1)": "Incident Response Testing | Automated Testing",
    "IR-3(2)": "Incident Response Testing | Coordination With Related Plans",
    "IR-4": "Incident Handling",
    "IR-4(1)": "Incident Handling | Automated Incident Handling Processes and Responses",
    "IR-4(2)": "Incident Handling | Dynamic Reconfiguration",
    "IR-4(3)": "Incident Handling | Continuity of Operations",
    "IR-4(4)": "Incident Handling | Information Correlation",
    "IR-4(5)": "Incident Handling | Automatic Disabling of Information System",
    "IR-4(6)": "Incident Handling | Insider Threats - Specific Capabilities",
    "IR-4(7)": "Incident Handling | Insider Threats - Intra-Organization Coordination",
    "IR-4(8)": "Incident Handling | Correlation With External Organizations",
    "IR-5": "Incident Monitoring",
    "IR-5(1)": "Incident Monitoring | Automated Tracking / Data Collection / Analysis",
    "IR-6": "Incident Reporting",
    "IR-6(1)": "Incident Reporting | Automated Reporting",
    "IR-7": "Establishment of Incident Response Capability",
    "IR-7(1)": "Establishment of Incident Response Capability | Automation Support For Availability",
    "IR-8": "Incident Response Plan",
    "IR-8(1)": "Incident Response Plan | Breaches",
    "IR-8(2)": "Incident Response Plan | Insider Threats",
    "IR-8(3)": "Incident Response Plan | Outsider Threats",
    "IR-8(4)": "Incident Response Plan | Malicious Insider Threats",
    "IR-9": "Information Spillage Response",
    "IR-9(1)": "Information Spillage Response | Responsible Personnel",
    "IR-9(2)": "Information Spillage Response | Training",
    "IR-9(3)": "Information Spillage Response | Post-incident Actions",
    "IR-9(4)": "Information Spillage Response | Exposure To Unauthorized Personnel",
    "IR-10": "Integrated Information Security Operations Center",
    "IR-10(1)": "Integrated Information Security Operations Center | Employ Automated Tools To Support Incident Handling Capability",

    # Risk Assessment (RA) Family
    "RA-1": "Risk Assessment Policies and Procedures",
    "RA-2": "Security Categorization",
    "RA-2(1)": "Security Categorization | Impact Analysis",
    "RA-3": "Risk Assessment",
    "RA-3(1)": "Risk Assessment | Supply Chain Risk Assessment",
    "RA-3(2)": "Risk Assessment | Use Of Specialized Tools and Techniques",
    "RA-3(3)": "Risk Assessment | Probabilistic Risk Analysis",
    "RA-3(4)": "Risk Assessment | Risk Assessment Update Triggers",
    "RA-3(5)": "Risk Assessment | Threat Characterization",
    "RA-4": "Threat Modeling",
    "RA-4(1)": "Threat Modeling | Supply Chain Threat Modeling",
    "RA-5": "Vulnerability Monitoring and Scanning",
    "RA-5(1)": "Vulnerability Monitoring and Scanning | Update Vulnerability Monitoring Tools",
    "RA-5(2)": "Vulnerability Monitoring and Scanning | Discover Vulnerabilities",
    "RA-5(3)": "Vulnerability Monitoring and Scanning | Programming Flaws and Logical Errors",
    "RA-5(4)": "Vulnerability Monitoring and Scanning | Internal Discoverable Weaknesses",
    "RA-5(5)": "Vulnerability Monitoring and Scanning | Privilege Escalation",
    "RA-5(6)": "Vulnerability Monitoring and Scanning | Automated Tools and Techniques",
    "RA-5(7)": "Vulnerability Monitoring and Scanning | Review Historic Vulnerability Information",
    "RA-5(8)": "Vulnerability Monitoring and Scanning | Review Malformed Input Processing",
    "RA-5(9)": "Vulnerability Monitoring and Scanning | Analyze Discovered Vulnerabilities",
    "RA-5(10)": "Vulnerability Monitoring and Scanning | Correlate Scan Tools Outputs",
    "RA-5(11)": "Vulnerability Monitoring and Scanning | Threat Waste Analysis",
    "RA-6": "Technical Surveillance Countermeasures Survey",
    "RA-6(1)": "Technical Surveillance Countermeasures Survey | Facility Characterization",
    "RA-7": "Risk Response",
    "RA-7(1)": "Risk Response | Risk Prioritization",
    "RA-8": "Privacy Impact Assessments",
    "RA-8(1)": "Privacy Impact Assessments | Privacy Threshold Analysis",
    "RA-9": "Criticality Analysis",
    "RA-9(1)": "Criticality Analysis | Critical Components and Services",
    "RA-10": "Supply Chain Risk Assessment",
    "RA-10(1)": "Supply Chain Risk Assessment | Information Exchange",
    "RA-10(2)": "Supply Chain Risk Assessment | Mapping Of Criticality",
    "RA-10(3)": "Supply Chain Risk Assessment | Criticality Of Supply Chain Elements",
    "RA-10(4)": "Supply Chain Risk Assessment | Sources Of Supply Chain Risk Information",

    # System and Information Integrity (SI) Family
    "SI-1": "System and Information Integrity Policies and Procedures",
    "SI-2": "Flaw Remediation",
    "SI-2(1)": "Flaw Remediation | Central Management",
    "SI-2(2)": "Flaw Remediation | Automated Flaw Remediation Status",
    "SI-2(3)": "Flaw Remediation | Time Limits For Flaw Remediation",
    "SI-2(4)": "Flaw Remediation | Automatic Flaw Remediation Updates",
    "SI-2(5)": "Flaw Remediation | Automatic Software / Firmware Updates",
    "SI-2(6)": "Flaw Remediation | Removal of Previous Versions of Software / Firmware",
    "SI-3": "Malicious Code Protection",
    "SI-3(1)": "Malicious Code Protection | Automatic Updates",
    "SI-3(2)": "Malicious Code Protection | Automatic Actions On Malicious Code Detection",
    "SI-3(3)": "Malicious Code Protection | Quarantine Capability",
    "SI-3(4)": "Malicious Code Protection | Update Malicious Code Protection",
    "SI-3(5)": "Malicious Code Protection | Grayware Identification and Handling",
    "SI-3(6)": "Malicious Code Protection | Testing and Verification",
    "SI-3(7)": "Malicious Code Protection | Nonsignature-based Detection",
    "SI-3(8)": "Malicious Code Protection | Grayware Protection",
    "SI-3(9)": "Malicious Code Protection | Malicious Code Protection For Mobile Code",
    "SI-3(10)": "Malicious Code Protection | Code And Signature Testing",
    "SI-4": "Information System Monitoring",
    "SI-4(1)": "Information System Monitoring | System-wide Intrusion Detection System",
    "SI-4(2)": "Information System Monitoring | Automated Tools for Real-time Analysis",
    "SI-4(3)": "Information System Monitoring | Integrate Security Operations With IT Operations",
    "SI-4(4)": "Information System Monitoring | Information System Monitoring",
    "SI-4(5)": "Information System Monitoring | System-generated Alerts",
    "SI-4(6)": "Information System Monitoring | Inbound and Outbound Communications Traffic",
    "SI-4(7)": "Information System Monitoring | Automated Response Capability",
    "SI-4(8)": "Information System Monitoring | Automated Response Capability",
    "SI-4(9)": "Information System Monitoring | Vulnerability Management Information Exchange",
    "SI-4(10)": "Information System Monitoring | Managed Threat Intelligence",
    "SI-4(11)": "Information System Monitoring | Analyze Communications Traffic Anomalies",
    "SI-4(12)": "Information System Monitoring | Automated Alerts and Advisories",
    "SI-4(13)": "Information System Monitoring | Analyze Network Traffic For Unauthorized Internal Connections",
    "SI-4(14)": "Information System Monitoring | Wireless Intrusion Detection",
    "SI-4(15)": "Information System Monitoring | Detect Unauthorized Wireless Access Points",
    "SI-4(16)": "Information System Monitoring | Correlate Monitoring Information",
    "SI-4(17)": "Information System Monitoring | Wireless Communications Monitoring",
    "SI-4(18)": "Information System Monitoring | Analyze Network Traffic For Unauthorized External Connections",
    "SI-4(19)": "Information System Monitoring | Deception Techniques",
    "SI-4(20)": "Information System Monitoring | Automated Threat Recognition and Response",
    "SI-4(21)": "Information System Monitoring | Sensor Visibility of Hardware Components",
    "SI-4(22)": "Information System Monitoring | Hardware-based Sensors",
    "SI-4(23)": "Information System Monitoring | Generate Alerts For Atypical Activities",
    "SI-5": "Security Alerts, Advisories, and Directives",
    "SI-5(1)": "Security Alerts, Advisories, and Directives | Automated Alerts and Directives",
    "SI-6": "Information System Monitoring",
    "SI-6(1)": "Information System Monitoring | Automated Tools",
    "SI-6(2)": "Information System Monitoring | Automated Tools and Techniques",
    "SI-7": "Software, Firmware, and Information Integrity",
    "SI-7(1)": "Software, Firmware, and Information Integrity | Cryptographic Mechanisms",
    "SI-7(2)": "Software, Firmware, and Information Integrity | Automated Monitoring and Reporting",
    "SI-7(3)": "Software, Firmware, and Information Integrity | Centralized Management",
    "SI-7(4)": "Software, Firmware, and Information Integrity | Automated Response To Integrity Violations",
    "SI-7(5)": "Software, Firmware, and Information Integrity | Automated Response To Integrity Violations",
    "SI-7(6)": "Software, Firmware, and Information Integrity | Cryptographic Protection",
    "SI-7(7)": "Software, Firmware, and Information Integrity | Integration With Organizational Processes",
    "SI-7(8)": "Software, Firmware, and Information Integrity | Automated Integrity Monitoring And Reporting",
    "SI-7(9)": "Software, Firmware, and Information Integrity | Verify Boot Process",
    "SI-7(10)": "Software, Firmware, and Information Integrity | Protect From Unauthorized Changes",
    "SI-7(11)": "Software, Firmware, and Information Integrity | Detect Unauthorized Changes",
    "SI-7(12)": "Software, Firmware, and Information Integrity | Firmware Integrity Verification",
    "SI-7(13)": "Software, Firmware, and Information Integrity | Code Signing and Verification",
    "SI-7(14)": "Software, Firmware, and Information Integrity | Binary or Machine Executable Code",
    "SI-8": "Information System Monitoring",
    "SI-8(1)": "Information System Monitoring | Automated Alerts and Notifications",
    "SI-8(2)": "Information System Monitoring | Automated Response Capability",
    "SI-9": "Information System Monitoring",
    "SI-9(1)": "Information System Monitoring | Automated Honeypots",
    "SI-10": "Information Input Validation",
    "SI-10(1)": "Information Input Validation | Application-level Validation",
    "SI-11": "Error Handling",
    "SI-11(1)": "Error Handling | Identify and Log",
    "SI-11(2)": "Error Handling | Reveal Error Messages Only To Authorized Individuals",
    "SI-12": "Information Handling and Retention",
    "SI-12(1)": "Information Handling and Retention | Minimize Personally Identifiable Information Processing",
    "SI-12(2)": "Information Handling and Retention | Minimize Personally Identifiable Information Processing",
    "SI-12(3)": "Information Handling and Retention | Data Handling",
    "SI-12(4)": "Information Handling and Retention | Retain System-generated Protect Information",
    "SI-13": "Predictable Failure Prevention",
    "SI-13(1)": "Predictable Failure Prevention | Automated Response Capability",
    "SI-13(2)": "Predictable Failure Prevention | Time-limit and Age-based Purging",
    "SI-13(3)": "Predictable Failure Prevention | Automated Resource Monitoring",
    "SI-13(4)": "Predictable Failure Prevention | Aging and Renewal",
    "SI-13(5)": "Predictable Failure Prevention | Adapt to Identified Anomalies",
    "SI-14": "Non-persistence",
    "SI-14(1)": "Non-persistence | Refresh From Trusted Sources",
    "SI-14(2)": "Non-persistence | Non-persistent Information System Components",
    "SI-15": "Information Output Filtering",
    "SI-15(1)": "Information Output Filtering | Automated Mechanisms",
    "SI-16": "Memory Protection",
    "SI-16(1)": "Memory Protection | Hardware Enforcement of Boundaries",
    "SI-17": "Fail Secure",
    "SI-17(1)": "Fail Secure | Failure Identification and Logging",
    "SI-18": "Personally Identifiable Information Quality Operations",
    "SI-18(1)": "Personally Identifiable Information Quality Operations | Data Quality Processes",
    "SI-18(2)": "Personally Identifiable Information Quality Operations | Data Correction and Deletion",
    "SI-18(3)": "Personally Identifiable Information Quality Operations | Collection and Maintenance",
    "SI-18(4)": "Personally Identifiable Information Quality Operations | Completeness and Currency",
    "SI-19": "Deception and Honeypots",
    "SI-19(1)": "Deception and Honeypots | Deployment In Isolated Environments",
    "SI-19(2)": "Deception and Honeypots | Distributed Deployment",
    "SI-19(3)": "Deception and Honeypots | Distributed Deployment Across Multiple Organizations",
    "SI-19(4)": "Deception and Honeypots | Automated Responses",
    "SI-20": "Information Residue",
    "SI-20(1)": "Information Residue | Residue Removal From Organization-controlled Sources",
    "SI-20(2)": "Information Residue | Residue Removal From External Sources",
    "SI-21": "Information Disclosure",
    "SI-21(1)": "Information Disclosure | Unauthorized Disclosure",
    "SI-22": "Information Integrity Monitoring and Response",
    "SI-22(1)": "Information Integrity Monitoring and Response | Automated Tools For Real-time Response",
}


def validate_nist_control(control_id: str) -> bool:
    """
    Validate that a control ID exists in NIST SP 800-53 R5 catalog.

    Args:
        control_id: Control ID to validate (e.g., 'SC-7', 'AC-2', 'CA-3')

    Returns:
        True if control exists, False otherwise
    """
    # Normalize to uppercase
    control_id = control_id.strip().upper()

    # Direct match
    if control_id in NIST_SP_800_53_R5_CONTROLS:
        return True

    # Try with different case variations
    for control in NIST_SP_800_53_R5_CONTROLS:
        if control.upper() == control_id:
            return True

    return False


def get_control_description(control_id: str) -> str:
    """
    Get the description of a NIST control.

    Args:
        control_id: Control ID to look up

    Returns:
        Control description if found, empty string otherwise
    """
    control_id = control_id.strip().upper()

    for control, description in NIST_SP_800_53_R5_CONTROLS.items():
        if control.upper() == control_id:
            return description

    return ""


def get_all_controls() -> list:
    """Get list of all valid NIST SP 800-53 R5 control IDs."""
    return list(NIST_SP_800_53_R5_CONTROLS.keys())


def get_control_family(control_id: str) -> str:
    """
    Extract the family code from a control ID.

    Args:
        control_id: Control ID (e.g., 'SC-7')

    Returns:
        Family code (e.g., 'SC')
    """
    control_id = control_id.strip().upper()

    # Extract family (first 2 letters before hyphen)
    if '-' in control_id:
        return control_id.split('-')[0]

    return ""
